steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |

      sed -i "s/_VER_/$BRANCH_NAME/" server/app.js


  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/gcptest-image:$BRANCH_NAME-$REVISION_ID', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/gcptest-image:$BRANCH_NAME-$REVISION_ID']


  # Update Deployment with new image  
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      
      sed -i "s/PROJECT_ID/$PROJECT_ID/" deploy.yaml
      sed -i "s/IMAGE_TAG/$BRANCH_NAME-$REVISION_ID/" deploy.yaml 

      export CLOUDSDK_COMPUTE_ZONE=asia-south1-a

      if [ $PROJECT_ID = "charlie-test-project-master" ]
      then        
        export CLOUDSDK_CONTAINER_CLUSTER=charlie-test-master
      else       
        export CLOUDSDK_CONTAINER_CLUSTER=testcluster
      fi
      
      /builder/kubectl.bash apply -f deploy.yaml --namespace=$BRANCH_NAME

