steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/gcptest-image', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/gcptest-image']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'testcluster', '--zone=asia-south1-a']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'run', 'gcp-test-app', '--image=gcr.io/${PROJECT_ID}/gcptest-image', '--port=8080' ]
    
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['expose', 'deployment', 'gcp-test-app', '--type=LoadBalancer', '--port=80', '--target-port=8080']


