steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/gcptest-image:$BRANCH_NAME-$REVISION_ID', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/gcptest-image:$BRANCH_NAME-$REVISION_ID']




