apiVersion: v1
kind: Service
metadata:
  name: gcp-test-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gcp-test-app

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcp-test-app
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: gcp-test-app
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/gcptest-image:IMAGE_TAG
        imagePullPolicy: Always
        name: gcp-test-app
        ports:
        - containerPort: 8080
        env:
        livenessProbe:

